insert into produto (descricao, valor) values ('Arroz 5kg',35)
insert into produto (descricao, valor) values ('Feijão 2kg',10)
insert into pessoa (tipo, nome, cpf) values ('F','Fulano','123123123')
insert into pessoa (tipo, nome, cnpj) values ('J','Mercadinho Silva','1234567890001')
insert into estado (id, nome, sigla) values (1, 'Tocantins', 'TO')
insert into cidade (nome, id_estado) values ('Palmas', 1)
insert into cidade (nome, id_estado) values ('Araguaína', 1)
insert into cidade (nome, id_estado) values ('Gurupi', 1)
insert into cidade (nome, id_estado) values ('Porto Nacional', 1)
insert into endereco (logradouro, complemento, bairro, id_cidade, id_pessoa) values ('Quadra 210 Sul, Alameda 10, n.10', 'Residencial', 'Centro', 1, 1)